version: '3.7'
services:
    # The Go App
    go-app:
        build: .
        container_name: go_app
        depends_on:
            - 'mongo'
        ports:
            - 8000:8000
        volumes:
            - './go-app:/opt/go-app:cached'
    # MongoDB
    mongo:
        image: 'mongo:4.2.6-bionic'
        container_name: mongocontainer
        ports:
            - 27017:27017
        volumes:
            - ./mongodata:/data/db
        restart: always
