version: '3.7'
services:
    # The Go App
    go-app:
        build: .
        container_name: go_app
        depends_on:
            - 'mongodb'
        environment:
            - PORT=8000
        ports:
            - '8000:8000'
        volumes:
            - './go-app:/opt/go-app:cached'
    # MongoDB
    mongodb:
        image: 'mongo:4.2.6-bionic'
        container_name: mongo
        ports:
            - '27100:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
